name: e-comerce

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      
      - name: Install staticchecks
        run: go get honnef.co/go/tools/cmd/staticcheck

      - name: Run staticcheck
        run: staticcheck -checks all,-U1000,-ST1000 ./app/...
      
      - name: Build
        run: go build -v ./...

      - name: Run Unit Tests
        run: go test -v ./...





